config/routes.rb
Rails.application.routes.draw do
  devise_for :readers
  devise_for :admin_users, controllers: { sessions: "admin/sessions" }, path: 'admin'
  namespace :admin do
    resources :animes
  end

  post 'tweets/:tweet_id/likes' => 'likes#create'
  post 'tweets/:tweet_id/likes/:id' => 'likes#destroy'

  get 'bye/thumb' => 'bye#thumb'
  get 'bye/pink' => 'bye#pink'

  root 'tweets#home'
  get 'tweets/home' => 'tweets#home'
  get 'tweets' => 'tweets#thumb'
  get 'tweets/thumb' => 'tweets#thumb'
  get 'tweets/rankingtotal', to:'tweets#rankingtotal'
  get 'tweets/ranking2000', to:'tweets#ranking2000'
  get 'tweets/ranking2010', to:'tweets#ranking2010'
  get 'tweets/ranking2015', to:'tweets#ranking2015'
  get 'tweets/ranking2020', to:'tweets#ranking2020'
  get 'tweets/ranking2025', to:'tweets#ranking2025'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/controllers/bye_controller.rb
class ByeController < ApplicationController
  def thumb
  end
  def pink
  end
end

app/helpers/bye_helper.rb
module ByeHelper
end

app/views/bye/pink.html.erb
You're gonna dancing!
<%= link_to 'Initial D', tweets_path %>
<%= link_to 'かもめおまみ', :controller=> "bye", :action => "thumb" %><br>
<%= link_to bye_thumb_path do %>
<%= image_tag '街　＃BGMバグってる.jpg', class:"logo-image" %>
<% end %>

app/views/bye/thumb.html.erb
<h1>neXt comiX</h1> 
<h3>「つぎ何読もう？」お困りのあなたへ</h3><br>
<h4>▶閲覧のみの方は</h4><%= link_to "マンガ紹介ページへ", tweets_path %><br>
<h4>▶コメントをする方はログインをしてから</h4><br>
STEP1 初めての方は<%= button_to "新規登録", new_reader_registration_path %>
STEP2 登録済みの方は<%= button_to "ログイン", reader_session_path %>
STEP3 ログインが終わったら<%= link_to "マンガ紹介ページへ", tweets_path %>