config/routes.rb
Rails.application.routes.draw do
  devise_for :readers
  devise_for :admin_users, controllers: { sessions: "admin/sessions" }, path: 'admin'
  namespace :admin do
    resources :animes
  end

  post 'tweets/:tweet_id/likes' => 'likes#create'
  post 'tweets/:tweet_id/likes/:id' => 'likes#destroy'

  get 'bye/thumb' => 'bye#thumb'
  get 'bye/pink' => 'bye#pink'

  root 'tweets#home'
  get 'tweets/home' => 'tweets#home'
  get 'tweets' => 'tweets#thumb'
  get 'tweets/thumb' => 'tweets#thumb'
  get 'tweets/rankingtotal', to:'tweets#rankingtotal'
  get 'tweets/ranking2000', to:'tweets#ranking2000'
  get 'tweets/ranking2010', to:'tweets#ranking2010'
  get 'tweets/ranking2015', to:'tweets#ranking2015'
  get 'tweets/ranking2020', to:'tweets#ranking2020'
  get 'tweets/ranking2025', to:'tweets#ranking2025'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :reader
  has_many :likes, dependent: :destroy
  has_many :liked_readers, through: :likes, source: :reader
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def home
    
  end
  def thumb
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
        @tweets = Tweet.where("title LIKE ? ",'%' + params[:search] + '%')
      end

      if params[:tag_ids]
        @tweets = []
        params[:tag_ids]. each do |key, value|
          @tweets += Tag.find_by(name: key).tweets if value == "1"
        end
        @tweets.uniq!
      end
    
      if params[:tag]
        Tag.create(name: params[:tag])
      end
    end
    def new
      @tweet = Tweet.new
    end

    def create
      tweet = Tweet.new(tweet_params)
      tweet.reader_id = current_reader.id
      if tweet.save
        redirect_to :action => "thumb"
      else
        redirect_to :action => "new"
      end
    end

    def show
      @tweet = Tweet.find(params[:id])
      @comments = @tweet.comments
      @comment = Comment.new
      @vote_results = Comment.where(tweet_id: @tweet.id).group(:vote_volume).count
    end

    def edit
      @tweet = Tweet.find(params[:id])
    end

    def update
      tweet = Tweet.find(params[:id])
      if tweet.update(tweet_params)
        redirect_to :action => "show", :id => tweet.id
      else
        redirect_to :action => "new"
      end
    end

    def ranking2000
      circulationtotwothousand = params[:circulationtotwothousand]
      @ranking_tweets = Tweet.order(circulationtotwothousand: :desc).limit(10)
    end

    def ranking2010
      circulationtotwentyten = params[:circulationtotwentyten]
      @ranking_tweets = Tweet.order(circulationtotwentyten: :desc).limit(10)
    end

    def ranking2015
      circulationtotwentyfifteen = params[:circulationtotwentyfifteen]
      @ranking_tweets = Tweet.order(circulationtotwentyfifteen: :desc).limit(10)
    end

    def ranking2020
      circulationtotwentytwenty = params[:circulationtotwentytwenty]
      @ranking_tweets = Tweet.order(circulationtotwentytwenty: :desc).limit(10)
    end

    def ranking2025
      circulationtotwentytwentyfive = params[:circulationtotwentytwentyfive]
      @ranking_tweets = Tweet.order(circulationtotwentytwentyfive: :desc).limit(10)
    end

    def rankingtotal
      circulationtotal = params[:circulationtotal]
      @ranking_tweets = Tweet.order(circulationtotal: :desc).limit(10)
    end
    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :thumb
    end

  private
  
  def tweet_params
    params.require(:tweet).permit(:title, :image, :about, :body, :author, :serialization, :volume, :circulationtotal, :circulation, :circulationtotwothousand, :circulationtotwentyten, :circulationtotwentyfifteen, :circulationtotwentytwenty, :circulationtotwentytwentyfive, :award, :app, tag_ids: [])
  end

  def if_not_admin
    redirect_to root_path unless current_reader.email == ENV['ADMIN_EMAIL']
  end
end

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %> 
      <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 75 %>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <%= f.label :about %>
  <%= f.text_area :about, :size => "80x10" %><br>
  <%= f.label :body %>
  <%= f.text_area :body, :size => "80x10" %> 
  <%= f.label :author %>
  <%= f.text_field :author, :size => 25 %><br>
  <%= f.label :serialization %>
  <%= f.text_field :serialization, :size => 75 %><br>
  <%= f.label :volume %>
  <%= f.number_field :volume, :size => 25 %><br>
  <%= f.label :circulationtotal %>
  <%= f.text_field :circulationtotal, :size=> 75 %><br>
  <%= f.label :circulation %>
  <%= f.number_field :circulation, :size => 50 %><br>
  <%= f.label :circulationtotwothousand %>
  <%= f.number_field :circulationtotwothousand, :size=> 25 %><br>
  <%= f.label :circulationtotwentyten %>
  <%= f.number_field :circulationtotwentyten, :size=> 25 %><br>
  <%= f.label :circulationtotwentyfifteen %>
  <%= f.number_field :circulationtotwentyfifteen, :size=> 25 %><br>
  <%= f.label :circulationtotwentytwenty %>
  <%= f.number_field :circulationtotwentytwenty, :size=> 25 %><br>
  <%= f.label :circulationtotwentytwentyfive %>
  <%= f.number_field :circulationtotwentytwentyfive, :size=> 25 %><br>
  <%= f.label :award %>
  <%= f.text_field :award, :size=> 75 %><br>
  <%= f.label :app %>
  <%= f.text_field :app, :size=> 75 %><br>
  <%= f.submit "編集" %>
<% end %>
がんばれ

app/views/tweets/home.html.erb
<%= stylesheet_link_tag "home", media: "all" %>

<div class= "main">
  <h2>とっておきのマンガが見つかる！<br>
  あなただけのマンガ検索サイト<br></h2>
  <div class="introduction-container">
    <div class="introduction-item">
      <h2>①細かくジャンル別で絞込検索<br></h2>
      <p>「次読みたいマンガがみつからない！」人におすすめの機能。
        様々なジャンルから今あなたが読みたいものをご提案します。<br>
      <div class="direction">
        <h4>早速「次読むマンガ」を画面右部分から検索！→</h4>
      </div></p><br>
    </div>
    <div class="introduction-item">
      <h2>②年代別ランキングで人気マンガをチェック<br></h2>
        <div class="comic-image">
          <%= image_tag 'ONE PIECE.jpg', :width => 250 %>
        </div>
      <p>「今の流行りだけじゃなくて、ちょっと前の人気作も読んでみたい！」人におすすめの機能。
      『スラムダンク』や『デスノート』など、懐かしの名作も年代ごとの発行部数からランキング化！</p><br>
    </div>
    <div class="introduction-item">
      <h2>③読者のナマの声が<br></h2>
        <div class="comic-image">
          <%= image_tag 'ONE PIECE.jpg', :width => 250 %>
        </div>
      <p>「じゃあ、実際どうなん？」と読むのをためらったそこのアナタ。読者コメントから
      </p><br>
    </div>
    <div class="introduction-item">
      <h2>④どのアプリから読めるかも一目瞭然！<br></h2>
      <p>「どこで読めるの？」読む気になってくれたアナタに       
      漫画アプリを紹介。</P>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<h3>新規マンガ作品紹介ページ</h3>
<%= form_for @tweet do |f| %>
  <div class='form-group'>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %> 
      <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>  
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size=> 75 %><br>
    <%= f.label :image %>
    <%= f.file_field :image %><br>
    <%= f.label :about %>
    <%= f.text_area :about, :size=>"80x5" %><br>
    <%= f.label :body %><br>
    <%= f.text_area :body, :size=>"80x10" %><br>
    <%= f.label :author %>
    <%= f.text_field :author, :size=> 25 %><br>
    <%= f.label :serialization %>
    <%= f.text_field :serialization, :size => 75 %><br>
    <%= f.label :volume %>
    <%= f.number_field :volume, :size => 25 %><br>
    <%= f.label :circulationtotal %>
    <%= f.text_field :circulationtotal, :size=> 75 %><br>
    <%= f.label :circulation %>
    <%= f.number_field :circulation, :size=> 50 %><br>
    <%= f.label :circulationtotwothousand %>
    <%= f.number_field :circulationtotwothousand, :size=> 25 %><br>
    <%= f.label :circulationtotwentyten %>
    <%= f.number_field :circulationtotwentyten, :size=> 25 %><br>
    <%= f.label :circulationtotwentyfifteen %>
    <%= f.number_field :circulationtotwentyfifteen, :size=> 25 %><br>
    <%= f.label :circulationtotwentytwenty %>
    <%= f.number_field :circulationtotwentytwenty, :size=> 25 %><br>
    <%= f.label :circulationtotwentytwentyfive %>
    <%= f.number_field :circulationtotwentytwentyfive, :size=> 25 %><br>
    <%= f.label :award %>
    <%= f.text_field :award, :size=> 75 %><br>
    <%= f.label :app %>
    <%= f.text_field :app, :size=> 75 %><br>
  </div>
  <%= f.submit "紹介" %>
<% end %>
<%= link_to "作品一覧に戻る", tweets_path %>

app/views/tweets/ranking2000.html.erb
<div class="main">
<div class="comic-container">
<h2>1999年以前の発行部数ランキング</h2>
  <div class="comic-items">
    <ol>
    <% @ranking_tweets.each do |tweet| %>
    <h3><li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulationtotwothousand %> 部
    </li></h3>
      <div class="comic-image">
        <%= image_tag tweet.image, width: 250 %>
      </div>
      <h4>ジャンル</h4>
        <% tweet.tags.each do |tag| %>
          <ol>＃<span><%= tag.name %></span></ol>
        <% end %>
      <h4>あらすじ</h4>
      <p><%= tweet.about %></p>

    <% end %>
    </ol>
  </div>
</div>
</div>
<%= stylesheet_link_tag "ranking2000", media: "all" %>

app/views/tweets/ranking2010.html.erb
<div class="main">
<div class="comic-container">
<h2>2000～2009年の発行部数ランキング</h2>
  <div class="comic-items">
    <ol>
    <% @ranking_tweets.each do |tweet| %>
    <h3><li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulationtotwentyten %> 部
    </li></h3>
      <div class="comic-image">
        <%= image_tag tweet.image, width: 250 %>
      </div>
      <h4>ジャンル</h4>
        <% tweet.tags.each do |tag| %>
          <ol>＃<span><%= tag.name %></span></ol>
        <% end %>
      <h4>あらすじ</h4>
      <p><%= tweet.about %></p>

    <% end %>
    </ol>
  </div>
</div>
</div>
<%= stylesheet_link_tag "ranking2010", media: "all" %>

app/views/tweets/ranking2015.html.erb
<h2>2011～2015年の発行部数ランキング</h2><ol>
  <% @ranking_tweets.each do |tweet| %>
    <li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulationtotwentyfifteen %> 部
    </li>
  <% end %>
</ol>

app/views/tweets/ranking2020.html.erb
<div class="main">
<div class="comic-container">
<h2>2015～2019年の発行部数ランキング</h2>
  <div class="comic-items">
    <ol>
    <% @ranking_tweets.each do |tweet| %>
    <h3><li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulationtotwentytwenty %> 部
    </li></h3>
      <div class="comic-image">
        <%= image_tag tweet.image, width: 250 %>
      </div>
      <h4>ジャンル</h4>
        <% tweet.tags.each do |tag| %>
          <ol>＃<span><%= tag.name %></span></ol>
        <% end %>
      <h4>あらすじ</h4>
      <p><%= tweet.about %></p>

    <% end %>
    </ol>
  </div>
</div>
</div>
<%= stylesheet_link_tag "ranking2020", media: "all" %>

app/views/tweets/ranking2025.html.erb
<div class="main">
<div class="comic-container">
<h2>2020～2024年の発行部数ランキング</h2>
  <div class="comic-items">
    <ol>
    <% @ranking_tweets.each do |tweet| %>
    <h3><li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulationtotwentytwentyfive %> 部
    </li></h3>
      <div class="comic-image">
        <%= image_tag tweet.image, width: 250 %>
      </div>
      <h4>ジャンル</h4>
        <% tweet.tags.each do |tag| %>
          <ol>＃<span><%= tag.name %></span></ol>
        <% end %>
      <h4>あらすじ</h4>
      <p><%= tweet.about %></p>

    <% end %>
    </ol>
  </div>
</div>
</div>
<%= stylesheet_link_tag "ranking2025", media: "all" %>

app/views/tweets/rankingtotal.erb
<div class="main">
<div class="comic-container">
<h2>累計発行部数ランキング</h2>
  <div class="comic-items">
    <ol>
    <% @ranking_tweets.each do |tweet| %>
    <h3><li>
      <%= link_to tweet.title, tweet_path(tweet) %> - <%= tweet.circulation %>
    </li></h3>
      <div class="comic-image">
        <%= image_tag tweet.image, width: 250 %>
      </div>
      <h4>ジャンル</h4>
        <% tweet.tags.each do |tag| %>
          <ol>＃<span><%= tag.name %></span></ol>
        <% end %>
      <h4>あらすじ</h4>
      <p><%= tweet.about %></p>

    <% end %>
    </ol>
  </div>
</div>
</div>
<%= stylesheet_link_tag "rankingtotal", media: "all" %>

app/views/tweets/show.html.erb
<%= stylesheet_link_tag "show", media: "all" %>

<div class="main">
<h1><p><%= @tweet.title %></p> </h1>
<div class="tweet">
  <div class="tweet-image">
    <%= image_tag @tweet.image, width: 250 %>
  </div>
  <h4>ジャンル</h4>
  <div class="genre">
    <% @tweet.tags.each do |tag| %>
      <ol>＃<span><%= tag.name %></span></ol>
    <% end %><br>
  </div>
  <h4>あらすじ</h4>
  <p><%= @tweet.about %></p>
  <h4>おすすめポイント！</h4>
  <p><%= @tweet.body %></p>
  <table>

  <h4>作者</h4>
  <p><%= @tweet.author %></p>
  <h4>連載状況</h4>
  <p><%= @tweet.serialization %></p>
  <h4>累計発行部数</h4>
  <p><%= @tweet.circulationtotal %></p>
  <h4>受賞など</h4>
  <p><%= @tweet.award %></p>
  <h4>この作品を無料で読めるアプリ</h4>
  <p><%= @tweet.app %></p>
  <% if reader_signed_in? && current_reader.email == ENV['ADMIN_EMAIL'] %> 
    <%= link_to "編集", edit_tweet_path(@tweet.id) %>
  <% end %><br>
</div>

<% if reader_signed_in? %>
      <% if current_reader.already_liked?(@tweet) %>
          <%= button_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
              <i class="fa-solid fa-thumbs-up"></i><%= @tweet.likes.count %>
          <% end %>
      <% else %>
          <%= button_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
              <i class="fa-solid fa-thumbs-up"></i><%= @tweet.likes.count %>
          <% end %>
      <% end %>
<% else %>
      <i class="fa-solid fa-thumbs-up"></i><%= @tweet.likes.count %>
<% end %><br>

<p><h4>読者みんなの「好きな巻」グラフ！</h4></p>
<canvas id="voteChart" width="1065" height="532" style="display: block; box-sizing: border-box; height: 355px; width: 710px;"></canvas>

<h3>いいねした読者</h3>
<% @tweet.liked_readers.each do |reader| %>
  <li><%= reader.email %></li>
<% end %>

<div class="comment-wrapper">
  <h3><p>読者の「ナマの声」</p></h3>
  <% @comments.each do |c| %>
    <div class="comment">
      <div class="left-container">
        <%= c.reader.email unless c.reader.blank? %><br>
        <%= c.content %>
      </div>
      <div id="comment-<%= c.id %>-rating"></div>
      <div class="right-container">
        <% if reader_signed_in? && current_reader.id == c.reader_id %>
          <%= button_to "削除", tweet_comment_path(c.tweet.id, c.id), method: :delete %>
        <% end %> 
        <p><%= c.created_at %></p>
      </div>
    </div>
      <br>
  <% end %>

  <% if reader_signed_in? %>
    <div id="rating-form">
      <%= form_with(model: [@tweet, @comment], local: false, id: "commentForm") do |f| %>
      <p>評価</p>
        <%= f.hidden_field :rate, value: 0, id: "comment_rate" %>
        <p>「何巻が好き？」を投票</p>
        <div class="volume-number">
          <div id="volume-buttons">
            <% (1..@tweet.volume).each do |volume| %>
              <button type="button" class="vote-button" data-volume="<%= volume %>">
                <%= volume %>巻
              </button>
            <% end %>
          </div>
        </div>
        <%= f.hidden_field :vote_volume, id: "selectedVolume" %>
        <%= f.label :content, "コメント" %>
        <%= f.text_area :content, :size => "60x5"  %>
        <p>※誹謗中傷などは削除される可能性がございます。</p>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメント投稿
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>


<!-- Chart.js の読み込み -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  // 投票ボタン -> hidden_field に値を入れる
  document.addEventListener("DOMContentLoaded", function() {
    const buttons = document.querySelectorAll(".vote-button");
    const hiddenInput = document.getElementById("selectedVolume");

    buttons.forEach(button => {
      button.addEventListener("click", function() {
        buttons.forEach(btn => btn.classList.remove("selected"));
        this.classList.add("selected");
        hiddenInput.value = this.dataset.volume;
      });
    });
  });

  // グラフ描画用のコード
  document.addEventListener("DOMContentLoaded", function() {
    // コントローラで作成した集計結果を JS のオブジェクトに変換
    var voteData = <%= raw @vote_results.to_json %>;
    
    var ctx = document.getElementById('voteChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: Object.keys(voteData).map(v => v + "巻"),
        datasets: [{
          label: '投票数',
          data: Object.values(voteData),
          backgroundColor: 'rgb(255, 236, 225)',
          borderColor: 'rgb(255, 94, 0)',
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: { beginAtZero: true }
        }
      }
    });
  });
</script>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    console.log("DOMContentLoaded イベント発火");

    const ratingForm = document.getElementById("rating-form");
    if (ratingForm && !ratingForm.dataset.ratyInitialized) {
      console.log("ratingForm に Raty を適用");
      new Raty(ratingForm, {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: "comment[rate]"
      });
      ratingForm.dataset.ratyInitialized = "true";
    }

    const comments = <%= raw(@comments.map { |c| { id: c.id, rate: c.rate || 0 } }.to_json) %>;
    comments.forEach(comment => {
      const commentRatingElement = document.getElementById(`comment-${comment.id}-rating`);
      if (commentRatingElement && !commentRatingElement.dataset.ratyInitialized) {
        console.log(`comment-${comment.id}-rating に Raty を適用`);
        new Raty(commentRatingElement, {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          readOnly: true,
          score: comment.rate
        });
        commentRatingElement.dataset.ratyInitialized = "true";
      }
    });
  });
</script>

<%= link_to "作品一覧に戻る", tweets_thumb_path %>
</div>

app/views/tweets/thumb.html.erb
<div class="main">
  <h3>検索結果</h3>
  <div class="tweets-container">
    <% @tweets.each do |t| %>
      <div class="tweet">
        <h2><%= link_to t.title, tweet_path(t.id) %></h2>
        <div class="comic-image">
          <% if t.image.attached? %>
            <%= image_tag t.image, width: 250 %>
          <% end %>
        </div>
        <h4>あらすじ</h4>
      <p><%= t.about %></p>
        <% if reader_signed_in? %>
          <% if current_reader.already_liked?(t) %>
            <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-thumbs-up"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
              <i class="fa-solid fa-thumbs-up"></i><%= t.likes.count %>              <% end %>
          <% end %>
        <% else %>
          <i class="fa-solid fa-thumbs-up"></i><%= t.likes.count %>
        <% end %>
        
        <% if reader_signed_in? && current_reader.email == ENV['ADMIN_EMAIL'] %> 
          <%= link_to "編集", edit_tweet_path(t.id) %>
          <%= button_to "削除", tweet_path(t.id), method: :delete %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= stylesheet_link_tag "application", media: "all" %>
<%= stylesheet_link_tag "thumb", media: "all" %>