config/routes.rb
Rails.application.routes.draw do
  devise_for :readers
  devise_for :admin_users, controllers: { sessions: "admin/sessions" }, path: 'admin'
  namespace :admin do
    resources :animes
  end

  post 'tweets/:tweet_id/likes' => 'likes#create'
  post 'tweets/:tweet_id/likes/:id' => 'likes#destroy'

  get 'bye/thumb' => 'bye#thumb'
  get 'bye/pink' => 'bye#pink'

  root 'tweets#home'
  get 'tweets/home' => 'tweets#home'
  get 'tweets' => 'tweets#thumb'
  get 'tweets/thumb' => 'tweets#thumb'
  get 'tweets/rankingtotal', to:'tweets#rankingtotal'
  get 'tweets/ranking2000', to:'tweets#ranking2000'
  get 'tweets/ranking2010', to:'tweets#ranking2010'
  get 'tweets/ranking2015', to:'tweets#ranking2015'
  get 'tweets/ranking2020', to:'tweets#ranking2020'
  get 'tweets/ranking2025', to:'tweets#ranking2025'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :reader
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :reader
  validates_uniqueness_of :tweet_id, scope: :reader_id
end

app/models/reader.rb
class Reader < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  has_many :comments, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :reader
  has_many :likes, dependent: :destroy
  has_many :liked_readers, through: :likes, source: :reader
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    if params[:controller].start_with?("readers/")
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    elsif params[:controller].start_with?("admin_users/")
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
      devise_parameter_sanitizer.permit(:account_update, keys: [:role])
    end
  end
end

app/controllers/bye_controller.rb
class ByeController < ApplicationController
  def thumb
  end
  def pink
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_reader!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.reader_id = current_reader.id
  
    if @comment.save
      respond_to do |format|
        if @comment.save
          format.html { redirect_to @comment.tweet, notice: 'Comment was successfully created.' }
          format.json { render json: { success: true, comment: @comment } }
        else
          format.html { render :new }
          format.json { render json: { success: false, errors: @comment.errors.full_messages }, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id], tweet_id: params[:tweet_id])
    @comment.destroy
    flash[:success] = "コメントを削除しました"
    redirect_to tweets_path
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :rate, :vote_volume)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_reader.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], reader_id: current_reader.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def home
    
  end
  def thumb
      if params[:search] == nil
        @tweets= Tweet.all
      elsif params[:search] == ''
        @tweets= Tweet.all
      else
        @tweets = Tweet.where("title LIKE ? ",'%' + params[:search] + '%')
      end

      if params[:tag_ids]
        @tweets = []
        params[:tag_ids]. each do |key, value|
          @tweets += Tag.find_by(name: key).tweets if value == "1"
        end
        @tweets.uniq!
      end
    
      if params[:tag]
        Tag.create(name: params[:tag])
      end
    end
    def new
      @tweet = Tweet.new
    end

    def create
      tweet = Tweet.new(tweet_params)
      tweet.reader_id = current_reader.id
      if tweet.save
        redirect_to :action => "thumb"
      else
        redirect_to :action => "new"
      end
    end

    def show
      @tweet = Tweet.find(params[:id])
      @comments = @tweet.comments
      @comment = Comment.new
      @vote_results = Comment.where(tweet_id: @tweet.id).group(:vote_volume).count
    end

    def edit
      @tweet = Tweet.find(params[:id])
    end

    def update
      tweet = Tweet.find(params[:id])
      if tweet.update(tweet_params)
        redirect_to :action => "show", :id => tweet.id
      else
        redirect_to :action => "new"
      end
    end

    def ranking2000
      circulationtotwothousand = params[:circulationtotwothousand]
      @ranking_tweets = Tweet.order(circulationtotwothousand: :desc).limit(10)
    end

    def ranking2010
      circulationtotwentyten = params[:circulationtotwentyten]
      @ranking_tweets = Tweet.order(circulationtotwentyten: :desc).limit(10)
    end

    def ranking2015
      circulationtotwentyfifteen = params[:circulationtotwentyfifteen]
      @ranking_tweets = Tweet.order(circulationtotwentyfifteen: :desc).limit(10)
    end

    def ranking2020
      circulationtotwentytwenty = params[:circulationtotwentytwenty]
      @ranking_tweets = Tweet.order(circulationtotwentytwenty: :desc).limit(10)
    end

    def ranking2025
      circulationtotwentytwentyfive = params[:circulationtotwentytwentyfive]
      @ranking_tweets = Tweet.order(circulationtotwentytwentyfive: :desc).limit(10)
    end

    def rankingtotal
      circulationtotal = params[:circulationtotal]
      @ranking_tweets = Tweet.order(circulationtotal: :desc).limit(10)
    end
    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
      redirect_to action: :thumb
    end

  private
  
  def tweet_params
    params.require(:tweet).permit(:title, :image, :about, :body, :author, :serialization, :volume, :circulationtotal, :circulation, :circulationtotwothousand, :circulationtotwentyten, :circulationtotwentyfifteen, :circulationtotwentytwenty, :circulationtotwentytwentyfive, :award, :app, tag_ids: [])
  end

  def if_not_admin
    redirect_to root_path unless current_reader.email == ENV['ADMIN_EMAIL']
  end
end

app/helpers/admin/animes_helper.rb
module Admin::AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bye_helper.rb
module ByeHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sweet_helper.rb
module SweetHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>neXt comiX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://kit.fontawesome.com/0f07c2fa61.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>neXt comiX</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_home_path %></li>
        <% if reader_signed_in? && current_reader.email == ENV['ADMIN_EMAIL'] %> 
          <li><%= link_to "新規作品紹介へ", main_app.new_tweet_path %></li>
        <% end %>
        <% if reader_signed_in? %>
          <%= button_to 'ログアウト', destroy_reader_session_path, method: :delete %>
        <% end %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
    <div class= "menu">
      <div class="catch-copy">
        <h2>つぎ何読む？</h2>
        <h4>ココから検索！</h4>
      </div>
      <h3><%= link_to "累計発行部数ランキング", tweets_rankingtotal_path %></h3>
      <h3>年代別人気漫画ランキング(発行部数)</h3>
      <%= link_to "～1999年", tweets_ranking2000_path %>
      <%= link_to "2000年～2009年", tweets_ranking2010_path %>
      <%= link_to "2010年～2014年", tweets_ranking2015_path %>
      <%= link_to "2015年～2019年", tweets_ranking2020_path %>
      <%= link_to "2020年～2024年", tweets_ranking2025_path %>
      <h3>マンガ検索</h3>
      ▼作品名から
      <%= form_tag(tweets_thumb_path, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索' %>
      <% end %>
      ▼ジャンルから絞り込み
      <%= form_tag(tweets_thumb_path, method: :get) do %>
          <% Tag.all.each do |t| %>
              <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
          <% end %>
          <%= submit_tag 'タグ検索' %>
      <% end %>
      <% if reader_signed_in? && current_reader.email == ENV['ADMIN_EMAIL'] %> 
        <%= form_tag({controller:"tweets",action:"thumb"}, method: :get) do %>
          <%= text_field_tag :tag %>
          <%= submit_tag 'タグを追加' %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>